### ISSUE TITLE
Few peers with kubernetes on kovan.

### ISSUE THREAD

**Issue by nathPay** [openethereum/openethereum#10781]
- **Parity Ethereum version**: v2.4.7-stable
- **Operating system**: Linux
- **Installation**: docker 17.03.3-ce
- **Fully synchronized**: no
- **Network**: kovan
- **Restarted**: yes
- **Kubernetes Version**: v1.14.2 deployed with RKE
- **Where**: AWS

I am running a kubernetes cluster of `parity/parity:stable` docker image.
This is a part of the .yml config file of my cluster:       

```
      containers:
      - image: parity/parity:stable
        name: kovan-parity
        args: [ "--chain", "kovan",   "--ipc-path", "/app/console.ipc", "--min-peers", "200", "--db-path", "/app/data", "--jsonrpc-interface", "0.0.0.0", "--jsonrpc-apis=web3,eth,net,pubsub,parity_pubsub,parity,traces,rpc,personal,parity_accounts,signer,parity_set", "--base-path", "/app/data" ]
        ports:
        - containerPort: 30303
          name: syncing
        - containerPort: 8545
          name: rpc
        - containerPort: 8546
          name: web-socket
```

The problem here is that peers number is very low (between 1 and 3) and sometime drop to 0.
If I use `parity --chain kovan` without kubernetes it's work well.
If I sync mainnet with kubernetes it's work.

What I've done:
- test with flannel, calico and canal for kubernetes networking
- repull docker image
- deleting all previous configuration
- use previous docker image version
- passing --bootnode parameter
- deleting all container (rke + kubernetes + parity) and force re pull

Hope you guys can give me some hint or ideas to debug this...
