### ISSUE TITLE
Using db reset for more than 64 blocks gives error

### ISSUE THREAD

**Issue by zemse** [openethereum/openethereum#11822]
- **OpenEthereum version**: 2.7.2
- **Operating system**: Linux
- **Installation**:  one-line installer
- **Fully synchronized**: yes
- **Network**: private
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

```
$ ./parity --config config.toml db reset 1000
Attempting to reset the chain 1000 blocks back failed: state is pruned (max available: 64)
```

But in the `config.toml` I already have enabled archive mode with:

```toml
[parity]
chain = "spec.json"
base_path = "/tmp/parity0"

[network]
port = 30300
reserved_only = true
reserved_peers = "./reserved_peers.txt"

[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
hosts = ["all"]
cors = ["all"]

[websockets]
port = 8450

[account]
password = ["node.pwds"]

[mining]
engine_signer = "0x36560493644fbb79f1c38d12ff096f7ec5d333b7"
force_sealing = true

[footprint]
tracing = "on"
pruning = "archive"
```

I already have `pruning = "archive"` but I am not able to reset blocks to more blocks. I want to have a full node of the chain in which no pruning is done (all transactions, receipts, states for all blocks).
