### ISSUE TITLE
OpenEthereum 3.0.1 Sync Slow?!!!

### ISSUE THREAD

**Issue by heimi-block** [openethereum/openethereum#11830]
OpenEthereum 3.0.1 Sync Satus:

Synchronization of initial blocks using openethereum 3.0.1 is slow

![截屏2020-07-27 下午7 43 41](https://user-images.githubusercontent.com/22029390/88538254-96d1b980-d041-11ea-96e0-01ca8882414e.png)

Compared with the synchronization using parity v2.5.13, parity has been synchronized to the latest
![截屏2020-07-27 下午7 44 01](https://user-images.githubusercontent.com/22029390/88538440-f3cd6f80-d041-11ea-919b-2217ad5df610.png)

Their configuration is almost the same, but why does openethereum's resynchronization effect on the main network is very poor. I used wrap, which started from 10000000, with a speed of only 0.2blocks

Is there anything wrong with me ?

**Comment by heimi-block** [comment]
Same issue here: https://github.com/openethereum/openethereum/issues/11753#issuecomment-637581476

I command start : --no-warp 
![image](https://user-images.githubusercontent.com/22029390/88608379-3334a400-d0b4-11ea-8ee4-905a69e48ee2.png)

But my origin want to 🔢 

# Disable syncing from the snapshot over the network.
warp = true

# When warp enabled never attempt regular sync before warping to block NUM. Current block - 10000
warp_barrier = 10111110

**Comment by heimi-block** [comment]
Update:

由ECS 4CPU/16RAM/NAS  升级为4CPU/16RAM/SSD，同步速度明显提升。
修改了很多配置，经过测试对比我运行的另外一个节点Parity v2.5.13
现在正确使用的config.toml如下：

```toml
[parity]
base_path = "/******/data"
chain = "foundation"
mode = "active"

no_consensus = false
no_download = false
no_persistent_txqueue = false
public_node = false

[network]
max_peers = 6
max_pending_peers = 64
min_peers = 3
port = 30301
snapshot_peers = 0
warp = true

[mining]
# Parity will keep/relay at most 32768 transactions in queue.
tx_queue_size = 32768
# Maximum number of transactions per sender in the queue. By default it's 1% of the entire queue, but not less than 16.
tx_queue_per_sender = 8192
# Prepare a block to seal even when there are no miners connected.
force_sealing = true

[rpc]
apis = ["all"]
cors = ["*"]
disable = false
hosts = ["all"]
interface = "0.0.0.0"
port = 39843

[websockets]
apis = ["all"]
disable = false
hosts = ["all"]
interface = "0.0.0.0"
max_connections = 100000
origins = ["*"]
port = 8547

[ipc]
disable = true

[footprint]
cache_size = 10240 // 10GB RAM
db_compaction = "ssd"
fast_and_loose = false
pruning = "fast"

[misc]
color = true
log_file = "/var/log/openethereum.log"
logging = "own_tx=trace"
```


![截屏2020-07-31 下午9 00 01](https://user-images.githubusercontent.com/22029390/89037309-d3b6ec80-d370-11ea-901e-559aa598ca2b.png)
